### ISSUE TITLE
Discard older status messages for switches/contact sensors

### ISSUE THREAD

**Issue by fx** [BobRak/OpenHAB-Smartthings#13]
Receiving events at `/smartthings/state` should include and discard any updates that are older than the current state for switches/contacts.

As is, if you rapidly open/close a contact, requests might arrive in any order and leave the contact in the wrong state until triggered again.

Haven't dug into where/how here, but seems pretty straightforward - include msec timestamp in request, compare to last update of thing?

**Comment by BobRak** [comment]
Just to make sure I understand, are you proposing that the hub includes a msec timestamp in the response. And, on the openHAB side I verify that no later request has already been received? Seems easy enough to implement. Do you think there are devices that will send that many events in a short time that this is an issue?

Do you think there could be the same issue on the hub side where messages get backed up and processed out of order? That seems like a harder problem to solve since some updates could come from places other that openhab. Changing a switch will generate an event and there is no timestamp there and no way to know if it is older than one received triggered by the smartthings app.

I'll look at adding this when I have time. At the moment I don't have a lot of time to devote to this.

**Comment by fx** [comment]
I can definitely see moments where a kid wiggles the door which leaves it in an open state despite being closed ;)

What would generate events for a smartthings thing other than the device/smartapp?

**Comment by BobRak** [comment]
I'm not going to make any more enhancements to this binding since there is a new Smartthing development environment.
