### ISSUE TITLE
Configuration

### ISSUE THREAD

**Issue by evgeni-g** [BobRak/OpenHAB-Smartthings#14]
Hi,

first of all: thanks for the great module. It is the first I amusing in GitHAB.

I followed your instructions very carefully and have set up everything correctly. However, I took me quite a while to configure the first device because I did not know that before you run the first auto discovery you have to add the smartings hub as a thing first. Maybe you could add this info to the instructions.

Also I saw that some things were no auto discovered automatically and some were.

For example in smartthings app I go to Smartapps-->OpenHabAppV2
Then I find the line named switch and add a few bulbs like KitchenBulb.

Then I go to OpenHAB and start auto discovery. The "kitchen bulb" is not found.
Then I click on add device manually, select switch and provide the kitchen bulb. Then it works.
Do you have an idea why the auto discovery does work for all devices?

Thanks
Evgeni

**Comment by BobRak** [comment]
Thank you very much for the feedback. I've done most of my configuration through files (because I have a cm11a (X10) device that doesn't support discovery). Therefore, my testing has been limited. I have updated the documentation. I am working at finishing up my own code review and testing in preparation for submitting it for inclusion as an official binding. I hope to push a new release to my github repo in the next couple of weeks.  

In my current testing everything was discovered. Maybe the missing things in your case will be resolved with the next code release.
