### ISSUE TITLE
Grouping sensors and attributes of one device into one item

### ISSUE THREAD

**Issue by unparagoned** [BobRak/OpenHAB-Smartthings#32]
It works really well thanks. It's even faster than than using the app 👍 The only comments I have are:

-  The readme could be a bit clearer, just before the openhab instructions should be instructions and links to how to set up the smartthings hub first. I was close to giving up before I went back and found the instruction about setting up the smartthings hub.

- Would it be possible to group the various sensors and attributes of a device under one item. At the moment the battery life of the multipurpose sensor is different all of it's sensors, so the one device acts like 5 separate items. It's mainly a cosmetic issue but it's much easier to have a one device - one item setup unless there is a really good reason not to. I noticed that the Arrival sensor has the link quality and received signal strength indicators under the same item, so I'm hoping it's not that much work to add in the other attributes such as battery, and presence to that item. 

- Is the alarm/alert function for the presence sensor something we can use? Is it something I can add with a bit of code or is it something that is not available to the public. 

Thanks again.

**Comment by BobRak** [comment]
Thanks for your feedback.  

**Re the readme:** 
I'll have a look at your pull request and incorporate that into the readme.

**Re grouping sensors and attributes**
Maybe I'm not following what you are asking but each item represents one item on the display and therefore if a device support multiple attributes there will have to be an item for each one you want to display.  And, in most cases there will have to be separate things because the type of attribute is different for each. That is just the way openHab works.

**Re presence sensor**
I assume you are talking about the Smartthings presence sensor. I don't own that device so I'm not an expert on it. According to the [Smartthings Capabilities reference](https://smartthings.developer.samsung.com/develop/api-ref/capabilities.html#Presence-Sensor)  it only support values of "not present" or "present."  Because openHab doesn't have the concept of presence I am returning those values as strings and therefore the item has to be setup as a String.

As I said in your other issue, I am in the process of preparing to move and therefore my responses may be delayed a few days.

Thanks,

Bob

**Comment by unparagoned** [comment]
The grouping of function may be complicated by the Samsung End in that it seems like they keep every function separate. It's just a presentational thing and helps make things easier. If you look at this picture you see the motion and multipurpose devices have their sensors all over the place as if they are completely different, it's a bit confusing and messy. If you look at the lamp plug, the switch, power and energy usage items are joined together as one thing. Which is how you usually do bindings in openhab. So you will have completely separate "items", which are joined together to make a "thing". At the moment you are making every "item" into a "thing", which isn't usually done in openhab.

![split](https://user-images.githubusercontent.com/10791552/36176102-717ba938-1109-11e8-83aa-7efb6b6f911a.png)

**Comment by BobRak** [comment]
Hi:

Sorry for the long delay in responding. Someday all of this moving business will be over and I can spend more time with openHAB.

The image from your last post appears to be from the paper UI. I haven't used it much. I did find an article onhow to group things using paper UI [Click here](https://community.openhab.org/t/groups-with-paper-ui/27729/5). I have been using the basic UI and configuring the display with a sitemap. This allows me to group things the way I want.  

I hope this is helpful.

**Comment by BobRak** [comment]
Hi:

Sorry for the delay in responding but I now finally have all of this moving business behind me. I updated the installation documentation to emphasize the Smartthings setup. I should depoly a new version in the next several days and it will be live then.

Bob
