### ISSUE TITLE
Basic question... instruction for where to put ''OpenHAB-Smartthings-master'' file ?

### ISSUE THREAD

**Issue by Garfield9988** [BobRak/OpenHAB-Smartthings#65]
Hi Bob, Community,

I am a new user and did ''Installation of Smartthings code'' with success.

For ''Samsung Smartthings Binding'' I don't see any instruction for where to put file/folder ''OpenHAB-Smartthings-master'' before applying step by step instruction. 

''Org.openhab.binding.smartthings-2.5.0-SNAPSHOT.jar'' need to be in ''openhab-2/addons'' folder ?

Other file need to be move in specific folder ?

Note: Using MacBook laptop with Mojave and java 8 Zulu 

Best Regards
Mart

**Comment by BobRak** [comment]
Hi Mart (@Garfield9988 )
Sorry the instructions are not better. That is my fault and I'll get some instructions added soon. In the past few days I made my final edits and submitted the binding to openHAB for review and eventual addition to their distribution. As part of that I removed the instructions for how to install it because once it is part of the openHAB platform the installation process is different.  So you can get it running here are the instructions I removed.

## Installation

Until this binding has been added to the OpenHAB repository you will need to copy the binding "jar" file to your OpenHAB server.

1. Locate the org.openhab.binding.smartthings-2.5.0-SNAPSHOT.jar file in the /target folder of the distribution.
2. Copy this file to the addons directory of your OpenHAB server. If you are using Openhabian this will be in the Samba share: openHAB/addons.
3. If openHAB is currently running it will need to be restarted (On Linux: sudo /etc/init.d/openhab2 stop followed by sudo /etc/init.d/openhab2 start)
4. Add the appropriate configuration files (.things, .items, .sitemaps)

The only file you need to copy is the **org.openhab.binding.smartthings-2.5.0-SNAPSHOT.jar** file.  Please let me know if you have additional questions.

**Comment by Garfield9988** [comment]
Hi Bob,

Did work perfectly !

All my 80 dimmer, door/window contact(Konnected), motion sensor, etc is there.

Great job!

I saw that Konnected have is specific binding but I do prefer to work like that for right now since I am a new user with OpenHAB.

I already did started to create my habpanel to look like ''atmoshome'' panel:
![Capture d’écran, le 2019-03-10 à 08 53 46](https://user-images.githubusercontent.com/31555748/54085528-88ccad00-4315-11e9-90fb-8d096f4eef42.jpg)

My actuel panel:
![Capture d’écran, le 2019-03-10 à 09 20 30](https://user-images.githubusercontent.com/31555748/54085563-ed880780-4315-11e9-86ea-8d083438005e.jpg)

I will add arm disarm panel and wish to find a way to add pin code security for disarming any idea ?

Regards
Mart

**Comment by Garfield9988** [comment]
Hi Bob,

For curious people....

I will control my habpanel from a iPad with ''www.smart-things.com'' wall mount:
<img width="763" alt="Capture d’écran, le 2019-03-10 à 09 36 43" src="https://user-images.githubusercontent.com/31555748/54085800-350f9300-4318-11e9-8749-93435c668250.png">
![Capture d’écran, le 2019-03-10 à 09 30 39](https://user-images.githubusercontent.com/31555748/54085801-40fb5500-4318-11e9-91b5-054214b5bd4b.jpg)

Also the ultimate goal is to remove completely my Samsung Smartthings hub to work with OpenHAB only and localy and reduce latency on system !!

I am also looking to get something to connect Leviton wifi dimmer DW6HD-1BZ ...did try 
''https://github.com/markcaldwell0017/python-decora_wifi-cli'' without succes unfortunaly !

I am planning big time to buy those 4 button Leviton wifi keypad, not wet available, and wish to have a binding.

![Capture d’écran, le 2019-03-10 à 09 47 49](https://user-images.githubusercontent.com/31555748/54085928-d0553800-4319-11e9-806b-79471549088a.jpg)

Mart

**Comment by BobRak** [comment]
Hi Mart:
Glad you got the binding installed and running. I did add another Readme.md file [here](https://github.com/BobRak/OpenHAB-Smartthings). I probably should have had a readme.md at this location all along. But, now this one includes the installation info and a path to the readme.md that will be included with the binding when it is deployed on the openHAB site.

I haven't done anything with HABPanel yet. But, now that I'm done with the binding, at least for now, maybe I'll take a look at it. I do know it is pretty extensible and it maybe possible to add a way to include a password field.

I don't have any ideas about how to integrate the Leviton wifi stuff. There is an HTTP binding. If the Leviton stuff has a published API then maybe that could be used. I've tried to stay away from wifi devices. I have a small house and already have 17 devices on my network. I don't have a feel for how many devices a router can support but wonder if there is a limit.

Bob
