### ISSUE TITLE
jobstate and machinestate

### ISSUE THREAD

**Issue by mario0658** [BobRak/OpenHAB-Smartthings#68]
Hi  
I have conected my washing machine , tumble dryer,  and I can see status of switch ( if is ON or OFF) 
It is possible to get machine state  ( status : prewash, wash, finishing etc)

![dish](https://user-images.githubusercontent.com/46091918/54500098-76580200-4919-11e9-9f69-618bddca950e.jpg)
![2222](https://user-images.githubusercontent.com/46091918/54500132-cf279a80-4919-11e9-85ff-0f0d11749e0b.jpg)

**Comment by BobRak** [comment]
Hi @mario0658 
I had a look at the smartthing capabilities list last night and they have added a bunch of new capabilities, most of them for their appliances. [You can see them here.](https://docs.smartthings.com/en/latest/capabilities-reference.html) I can work at adding these but I don't have any way to test them since I don't own any of these appliances. 

One thing I'm not certain about is if these are working on the Smartthings side. If you look at the capabilities list you will see all of these new appliance capabilities have a status of proposed where the rest have a status of live.

Could you do some testing for me since you seem to own a number of the appliances? I could update the smartthings code first and put it somewhere for you to pick it up. And, I would give you some CURL commands to execute to see that it works as expected. you would have to download and install CURL from [here](https://curl.haxx.se/download.html).

It will a at least a few weeks before I can get this done.

**Comment by mario0658** [comment]
Hi  
For me is no problem to give You full  control   of my  smartthings hub.

login   for ST  : koziaramariusz74@gmail.com
pass : mercedes320

some  apliance have polish names but I think is not big problem 

My whatsUp / Signal  +48 511271041 for flash message  , don’t forgot my time is greenwich  time +1 h      ( I’m  from Poland – Europe)  
Much better I can speak than write   
For this moment I using only mQtt bridge  to openhab 2.3.0 so You can change what You need in this app.



Mariusz Koziara
tel.511 27 10 41

**Comment by BobRak** [comment]
Hi:
I am getting back to working on the openHAB smartthings binding. Sorry this has been so long in coming but things have kept getting in the way. In the past year and a half I have lived in 3 different places, sold and bought houses. Plus, openHAB has redone the build system and for a long time it was just unstable.

Are you still interested in this these capabilities? If so, can you do some testing since I don't own these appliances.

Thanks,

Bob

**Comment by mario0658** [comment]
Of course yes 😎
It You need to do some tests is no problem. You can use my hub. Log details
is exacly same.
My whatsUp +48511271041
Skype Mariusz koziara in Poland.
Koziaramariusz1974@gmail.com


pt., 10 sty 2020, 17:52 użytkownik Bob Raker <notifications@github.com>
napisał:

**Comment by BobRak** [comment]
Hi Mario:

Believe it or not, I have finally added support for the DryerMode and DryerOperatingState capabilities.  I have uploaded a new jar file to https://github.com/BobRak/OpenHAB-Smartthings. I have also created sample config files which you can find at: https://github.com/BobRak/Smartthings-SimulatedDryer. And, in that same repo I had added a Simulated Dryer Device Handler. I created this so I could test the dryer capabilities.

**Comment by mario0658** [comment]
Hi.
Very cool news 😀
Maybe today evening I try to install new jar.
I let You know asap.
Take care about virus 😎

wt., 7 kwi 2020, 23:27 użytkownik Bob Raker <notifications@github.com>
napisał:

**Comment by BobRak** [comment]
I just made some minor changes. I don't think they would affect jobstate and machinestate. When you get a chance can you see if those capabilities now work. Since I am on a roll I would like to get this finished up and submitted to openHAB for addition to the core set of bindings.
Please stay safe

**Comment by mario0658** [comment]
Hi 
yesterday I start work with smartthings.
For now is working 
I’am not expert so I need lots of testing OpenHub before .
Thank You for Yours time 

Mariusz Koziara
tel.511 27 10 41

**Comment by BobRak** [comment]
OK, let me know if you discover any issues. For now I'll close the issue. Even though it is closed you can add to it and I'll get notified.

Bob
