### ISSUE TITLE
Smarththings Multipurpose Sensor doesn't report updates

### ISSUE THREAD

**Issue by Nannak** [BobRak/OpenHAB-Smartthings#72]
Firstly, great work on the SmartThings integration, very straightforward to install and works really well (mostly!).

I am having an issue with the Multipurpose sensor (contact, temp, humidity) not reporting back to openHab (2.4).

The log states:
2019-05-12 16:46:39.114 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler SmartthingsThingHandler of thing smartthings:contactSensor:da384dc0:MB_Ceiling_Sensor tried updating channel contact although the handler was already disposed.
2019-05-12 16:48:56.590 [WARN ] [.core.thing.binding.BaseThingHandler] - Handler SmartthingsThingHandler of thing smartthings:temperatureMeasurement:da384dc0:MB_Ceiling_Sensor tried updating channel temperature although the handler was already disposed.

Any help much appreciated (hopefully this is the correct place to post this?).

**Comment by BobRak** [comment]
@Nannak Please make sure that you do not have 2 smartthings jar files (with different version numbers) in your addons directory. If that isn't the issue let me know.

Bob

**Comment by Nannak** [comment]
Just the one file:
 
org.openhab.binding.smartthings-2.5.0-SNAPSHOT.jar
 
Although I should say, running on a Synology Diskstation (DSM6.3).
 
Thanks!
-----Original Message-----

**Comment by BobRak** [comment]
Hi @Nannak 
Have a look at [issue 69](https://github.com/BobRak/OpenHAB-Smartthings/issues/69) and in particular look at the section from April 26 where I ask him to check for multiple copies of the smartthings binding install. To me the messages you are getting indicates there are two copies if the binding installed.

Let me know. FYI, I am out of town for most of this month. I'll answer when I can.

Bob

**Comment by Nannak** [comment]
So checked for multiple copies, unfortunately it appears only the 2.5 version is running:

openhab> bundle:list | grep -i smartthings                                      
220 │ Active   │  80 │ 2.5.0.201904051837     │ Smartthings Binding

and there are no other entries...

**Comment by BobRak** [comment]
@Nannak 
I'm at a loss as to what the problem might be. Here are a couple of suggestions but don't have a strong feeling that either will fix things for you

1. Have a look at the following article about [jasondb storage](https://www.openhab.org/docs/administration/jsondb.html). I am wondering if the same device may have been discovered twice? Just a guess on my part and a suggestion.

2. Have a look at [issue #69](https://github.com/BobRak/OpenHAB-Smartthings/issues/69). He is also using the synology diskstation. He had different issues but something to look at and someone else to contact if you want.

3. Try manual configuration (using files instead of the PaperUI). If you try this you will have to delete the smartthings hub in the paperui first.

I'm leaving tomorrow and will be out of town through the end of May. I'll have somewhat limited internet access but I'll respond when I can.

Bob

**Comment by pocupine** [comment]
Hi,
I had problem previously when one side lost communication with another side for a long time. One day I pulled the plug of smartthings hub off then replugged it then they started to work flawlessly. It happened
on another time. It gave me a feeling that openhab and smartthings would lose communication sometimes for some reasons. It was quite random and I don't have the knowledge to find out what were the reasons. But restarting did fix the problem. Please have a try. Thanks.
